config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root "application#home"
  root "pages#hello"
  get "/about",to:"pages#about"
  get "/help", to: "pages#help"
  #get "/todos", to: "todos#todos"
  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auteur.rb
class Auteur < ApplicationRecord
end

app/models/cour.rb
class Cour < ApplicationRecord
	validates :coef, length:{maximum: 1,wrong_length: "%{count} à determiner...", too_long:"Le nombre %{value} n'est pas authorisé ..."}

  validates_each :nom_c do |record, attr, value|
    record.errors.add(attr, 'La premiere lettre doit etre une majuscule...') if value =~ /\A[[:lower:]]/
  end
#validates :nom_c, presence: {message: "le nom est obligatoire..."}

  validates :nom_c,
    uniqueness: {
      # object = person object being validated
      # data = { model: "Person", attribute: "Username", value: <username> }
      message: ->(object, data) do
        "Hey #{object}!, #{data[:value]} is taken already! Try again #{Time.zone.tomorrow}"
      end
    }
end

app/models/eleve.rb
class Eleve < ApplicationRecord
	validates :nom, presence:true
  after_initialize do |eleve|
    puts "Objet crée avec succès!!!"
  end
 
  after_find do |eleve|
    puts "Objet trouvé!!!"
  end
end

app/models/livre.rb
class Livre < ApplicationRecord
  belongs_to :auteur
end

app/models/todo.rb
class Todo < ApplicationRecord
	validates :name, presence: {message: "La saisie du nom est obligatoire..."}
	validates :name, length: {minimum: 3 , message: "Le nom doit avoir au moins 3 caratères..."}
	validates :description, presence: {message: "La description est obligatoire..."}
  def a_method_used_for_validation_purposes
    errors.messages[:name] << "cannot contain the characters !@#%*()_-+="
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def hello
	end

	def about

	end

	def help
	end
end 

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only:[:show,:edit,:destroy]

  def index
  	@todos = Todo.all
  end

  def new
  	@todo = Todo.new
  end

  def create
  	@todo = Todo.new todos_params
  	if @todo.save
  		flash[:notice] = "Ajout effectué avec succès..."
  		redirect_to todo_path @todo
  	else
  		render 'new'
  	end
  end

  def show
  	set_todo
  end

  def edit
  	set_todo
  end

  def update
  	 
  	if @todo.update todos_params
  		flash[:notice] = "Mise à jour effectué avec succès..."
  		redirect_to todo_path @todo
  	else
  		render 'edit'
  	end
  end

  def destroy
  	set_todo
  	@todo.destroy
  	flash[:notice] = "Tache supprimée avec succès!!!"
  	redirect_to todos_path
  end
  private

  	def set_todo
  		@todo = Todo.find params[:id]
  	end

  	def todos_params
  		params.require(:todo).permit(:name,:description)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
 <ul>
    <% flash.each do |nom, msg| %>
      <li><%= msg %></li>
    <%end%>
  </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h3>******* About **********</h3>
<% puts "Test..."%>

app/views/pages/hello.html.erb
<h3>********Hello World**********</h3>
<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/pages/help.html.erb
<h3>********* Help *******</h3>

<%= image_tag 'unnamed.png', style: 'height:100px;width:400px;' %>

app/views/todos/_form.html.erb
<% if @todo.errors.any? %>
	<h2>impossible d'effectuer l'opération : </h2>
	<ul>
		<% @todo.errors.messages.each do |n,msg| %>
			<% msg.each do |e| #msg est un tableau %>
				<li>
					<%= e %>
				</li>
			<%end%>	
		<%end%>		
	</ul>
<%end%>


<%= form_for @todo, html: {class: "nifty_form"} do |f| %>
	<p>
		<%= f.label :name, "Nom : " %><br>
		<%= f.text_field :name %>
	</p>
  
  	<p>	
  		<%= f.label :description, "Description : " %><br>
  		<%= f.text_area :description, size: "60x12" %>
  	</p>
  
  	<p>
  		<%= f.submit "Valider" %>
  	</p>
<%end%>

<p><%= link_to "Consulter la liste des Taches", todos_path %></p>

app/views/todos/edit.html.erb
<h1>Mise à jour de Tache :</h1>

<%= render 'form' %>

app/views/todos/index.html.erb
<h1>Liste des Globale des Taches</h1>

<p><%= link_to "créer une nouvelle tache", new_todo_path %></p>

<table>
	<tr>
		<th>Tache</th>
		<th>Description</th>
		<th></th>
	</tr>


	<% @todos.each do |t| %>
		<tr>
			<td>
			<%= link_to t do %>
				<strong><%= t.name %></strong>
			<%end%>
			</td>
			<td><%= t.description %></td>
			<td><%= link_to "Editer", edit_todo_path(t) %></td>
			<td><%= link_to "Supprimer", todo_path(t), method: :delete, data: {confirm: "
				attention, svp, Confirmez la Suppression..."}  %></td>
		</tr>
	<%end%>

</table>

app/views/todos/new.html.erb
<h1>Création d'une Tache</h1>

<%= render 'form' %>

app/views/todos/show.html.erb
<p><strong>Nom de la tache :</strong><%= @todo.name%></p>
<p><strong>Description: </strong><%= @todo.description%></p>

<p><%= link_to "Consulter la liste des Taches", todos_path %></p>

app/views/todos/todos.html.erb
<h4>********** ToDos____</h4>